name: Documentation

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/web/pages/docs/**'
      - 'apps/web/src/components/docs/**'
      - 'apps/web/scripts/docs-*.js'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/web/pages/docs/**'
      - 'apps/web/src/components/docs/**'
      - 'apps/web/scripts/docs-*.js'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Validate documentation
        run: npm run docs:validate

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docs-validation-report
          path: apps/web/docs-validation-report.json

  build:
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run docs:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: apps/web/.next/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: apps/web/.next/

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
          working-directory: apps/web
          vercel-args: '--prod'

  preview:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: apps/web/.next/

      - name: Deploy preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
          working-directory: apps/web
          vercel-args: '--prod=false'

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📚 **Documentation Preview**\n\nYour documentation changes are ready for review: ${{ steps.deploy.outputs.preview-url }}`
            })